# Generated by Django 2.1.3 on 2019-05-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textiles', '0013_auto_20190518_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='cover_image',
            field=models.ImageField(default='/static/img/1.jpg', upload_to=''),
        ),
    ]
